/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

//import java.awt.Color;
//import static java.lang.System.exit;
import javax.swing.JFrame;
//import javax.swing.JLabel;
import javax.swing.JOptionPane;
//import javax.swing.JPanel;
//import javax.swing.UIManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class login1 extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
     
    /**
     * Creates new form login1
     */
    public login1() {
        setLocation(270,170);
        setUndecorated(true);
        initComponents();
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        passwd = new javax.swing.JPasswordField();
        combo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rod_of_asclepius_127px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 420));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_rod_of_asclepius_50px_1.png"))); // NOI18N
        jLabel3.setText("NEWLIFE PHARMACEUTICALS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_37px.png"))); // NOI18N
        jLabel7.setText("User name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_password_37px.png"))); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 36));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_clear_symbol_37px.png"))); // NOI18N
        jButton1.setToolTipText("Clear the values entered");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 89, -1));

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_go_37px.png"))); // NOI18N
        jButton2.setToolTipText("Enter to your account");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 90, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 230, 30));

        passwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdActionPerformed(evt);
            }
        });
        jPanel1.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 230, 30));

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT OPTION", "ADMIN", "PHARMACIST" }));
        combo.setToolTipText("Select whether you are an admin or an employee");
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_48px_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 40));

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if(combo.getSelectedItem().equals("ADMIN"))
            {
                
                
                     if(String.valueOf(passwd.getPassword()).equals("") || username.getText().equals(""))
                        {
                          /*UIManager ui = new UIManager();
                          ui.put("OptionPane.background", Color.BLUE);
                          ui.put("Panel.background", Color.BLUE);*/
                            
                            JOptionPane.showMessageDialog(null,"Enter Username and Password!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION);
                        }
                        else
                        {
                         try {
                             Class.forName("com.mysql.jdbc.Driver");
                             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root","");
                             Statement stm=con.createStatement();
                             String user = username.getText();
                             String pass = String.valueOf(passwd.getPassword());
                             String q = "Select username,passwd from users where username = '" + user + "' AND passwd = '" +pass+"'"+" AND admins = " +"1";
                             ResultSet rs = stm.executeQuery(q);
                             if(rs.next())
                             {
                                 setVisible(false);
                               
                    admin_window ad = new admin_window(username.getText());
                    
                    ad.setVisible(true); 
                             }
                            else
                             {
                                 JOptionPane.showMessageDialog(null,"Incorrect Username and Password!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION);
                             }
                            
                         } catch (SQLException ex) {
                             Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
                         } catch (ClassNotFoundException ex) {
                             Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
                         }
                      
                        }
                 
            }
            else if(combo.getSelectedItem().equals("PHARMACIST") )
                    {
                        if(passwd.getText().equals("")&& username.getText().equals(""))
                        {
                            JOptionPane.showMessageDialog(null,"Enter Username and Password!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION);
                        }
                        else
                        {
                                    try {
                             Class.forName("com.mysql.jdbc.Driver");
                             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root","");
                             Statement stm=con.createStatement();
                             String user = username.getText();
                             String pass = String.valueOf(passwd.getPassword());
                             String q = "Select username,passwd from users where username = '" + user + "' AND passwd = '" +pass+"'" +" AND admins = " +"0" ;
                             ResultSet rs = stm.executeQuery(q);
                             if(rs.next())
                             {
                                 setVisible(false);
                    employeew em = new employeew(user);
                    em.setVisible(true); 
                             }
                            else
                             {
                                 JOptionPane.showMessageDialog(null,"Incorrect Username and Password!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION);
                             }
                            
                         } catch (SQLException ex) {
                             Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
                         } catch (ClassNotFoundException ex) {
                             Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
                         }
                        }
                    
                    }
            
           else
                   {
                     JOptionPane.showMessageDialog(null,"Please select an option first!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION);
                   }
        
      
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
     
                          
    
             
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        username.setText("");
        passwd.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_comboActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
       
     if(JOptionPane.showConfirmDialog(frame, "Do you want to Exit!","Newlife Pharmaceuticals",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
     {
         System.exit(0);
     }
     
         
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdActionPerformed
        // TODO add your handling code here:
    jButton2ActionPerformed(evt);
    }//GEN-LAST:event_passwdActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
           passwd.setFocusable(true);
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
               
                new login1().setVisible(true);
                
            }
        });
 
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
